---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: banafam-gnome
description: A tweaked version of Bluefin Linux with 1Password, Ghostty, and Vivaldi

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: bling
    install:
      - 1password
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/scottames/ghostty/repo/fedora-%OS_VERSION%/scottames-ghostty-fedora-%OS_VERSION%.repo
      - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
    install:
      - ghostty
      - vivaldi-stable
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
