---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: banafam-gnome
# description will be included in the image's metadata
description: A tweaked version of Bluefin Linux with 1Password, Ghostty, and Firefox

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: bling
    install:
      - 1password
  - type: rpm-ostree
    repos:
      - foo
    install:
      - ghostty
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
